Repository woowa-techcamp-2024/Team5-Guys, pull requests merged in 2024-08, with the labels that each got.

#6 Feat/#4: LogBat 서버 세팅
  .gitignore
  logbat/.gitignore
  logbat/build.gradle
  logbat/gradle/wrapper/gradle-wrapper.jar
  logbat/gradle/wrapper/gradle-wrapper.properties
  logbat/gradlew
  logbat/gradlew.bat
  logbat/settings.gradle
  logbat/src/main/java/info/logbat/LogbatApplication.java
  logbat/src/main/resources/application.properties
Labels: 🚀 Infra

#7 Style/#3 README.md 생성
  README.md
Labels: 📑 Docs, 💇🏻‍♀️ Style

#11 AI 코드 리뷰 도입
  .github/workflows/code-review.yml
Labels: ⭐️ Feat, 🧹 Chore

#32 Feat/#17 Project Service CRUD 구현
  logbat/src/main/java/info/logbat/common/config/JpaConfiguration.java
  logbat/src/main/java/info/logbat/domain/project/application/ProjectService.java
  logbat/src/main/java/info/logbat/domain/project/domain/Project.java
  logbat/src/main/java/info/logbat/domain/project/presentation/payload/request/ProjectUpdateRequest.java
  logbat/src/main/java/info/logbat/domain/project/presentation/payload/response/ProjectCommonResponse.java
  logbat/src/main/java/info/logbat/domain/project/repository/ProjectJpaRepository.java
  logbat/src/test/java/info/logbat/domain/project/application/ProjectServiceTest.java
  logbat/src/test/java/info/logbat/domain/project/domain/ProjectTest.java
Labels: ⭐️ Feat

#35 Feat/#14 JS SDK mvp1을 제작한다
  sdk/js/.gitignore
  sdk/js/README.md
  sdk/js/jest.config.js
  sdk/js/package-lock.json
  sdk/js/package.json
  sdk/js/src/__tests__/index.test.ts
  sdk/js/src/index.ts
  sdk/js/tsconfig.json
  sdk/js/webpack.config.js
Labels: 📑 Docs, 🚀 Config, ⭐️ Feat

#42 Feat/#19 App Key 생성 및 서비스 구현
  logbat/src/main/java/info/logbat/domain/project/application/AppService.java
  logbat/src/main/java/info/logbat/domain/project/domain/App.java
  logbat/src/main/java/info/logbat/domain/project/presentation/payload/response/AppCommonResponse.java
  logbat/src/main/java/info/logbat/domain/project/repository/AppJpaRepository.java
  logbat/src/test/java/info/logbat/domain/project/application/AppServiceTest.java
  logbat/src/test/java/info/logbat/domain/project/domain/AppTest.java
Labels: ⭐️ Feat

#49 Feat/#46 [💡 FEAT] AI 코드 리뷰 도입 V2
  .github/workflows/code-review.yml
Labels: 🚀 Config, ⭐️ Feat

#50 Feat/#48 App API 구현
  logbat/src/main/java/info/logbat/domain/project/application/AppService.java
  logbat/src/main/java/info/logbat/domain/project/presentation/AppController.java
  logbat/src/main/java/info/logbat/domain/project/presentation/payload/request/AppCreateRequest.java
  logbat/src/main/java/info/logbat/domain/project/repository/AppJpaRepository.java
  logbat/src/test/java/info/logbat/domain/common/ControllerTestSupport.java
  logbat/src/test/java/info/logbat/domain/project/application/AppServiceTest.java
  logbat/src/test/java/info/logbat/domain/project/presentation/AppControllerTest.java
Labels: ⭐️ Feat

#59 Feat/#58 View Server - DB Entity, Domain Entity 구현
  logbat_view/build.gradle
  logbat_view/src/main/java/info/logbat_view/domain/log/domain/Log.java
  logbat_view/src/main/java/info/logbat_view/domain/log/domain/LogData.java
  logbat_view/src/main/java/info/logbat_view/domain/log/domain/enums/LogLevel.java
  logbat_view/src/main/java/info/logbat_view/domain/log/domain/service/LogService.java
  logbat_view/src/main/java/info/logbat_view/domain/log/repository/LogDataRepository.java
  logbat_view/src/test/java/info/logbat_view/domain/log/domain/service/LogServiceTest.java
Labels: ⭐️ Feat

#65 Feat/#54 요청 처리 수를 확인하는 API 추가
  logbat/src/main/java/info/logbat/dev/aop/CountTest.java
  logbat/src/main/java/info/logbat/dev/aop/CountTestAspect.java
  logbat/src/main/java/info/logbat/dev/presentation/CountTestController.java
  logbat/src/main/java/info/logbat/dev/presentation/payload/response/CountTestResponse.java
  logbat/src/main/java/info/logbat/dev/service/CountTestService.java
  logbat/src/main/java/info/logbat/dev/service/DivideCountTestService.java
  logbat/src/main/java/info/logbat/dev/service/LongAdderCountTestService.java
  logbat/src/main/java/info/logbat/dev/service/SimpleCountTestService.java
  logbat/src/main/java/info/logbat/dev/util/ThreadLocalLongAdder.java
  logbat/src/main/java/info/logbat/domain/log/presentation/LogController.java
  logbat/src/test/java/info/logbat/dev/presentation/CountTestControllerTest.java
  logbat/src/test/java/info/logbat/dev/service/CountTestServiceTest.java
  logbat/src/test/java/info/logbat/dev/service/DivideCountTestServiceTest.java
  logbat/src/test/java/info/logbat/dev/service/LongAdderCountTestServiceTest.java
  logbat/src/test/java/info/logbat/dev/service/SimpleCountTestServiceTest.java
  logbat/src/test/java/info/logbat/dev/util/ThreadLocalLongAdderTest.java
  logbat/src/test/java/info/logbat/domain/common/ControllerTestSupport.java
Labels: ⭐️ Feat

#69 Feat/#64 Nginx 요청 Count API 구현
  nginx/.gitignore
  nginx/fastcgi.conf
  nginx/fastcgi_params
  nginx/koi-utf
  nginx/koi-win
  nginx/mime.types
  nginx/nginx.conf
  nginx/proxy_params
  nginx/scgi_params
  nginx/sites-available/default
  nginx/sites-enabled/default
  nginx/snippets/fastcgi-php.conf
  nginx/snippets/snakeoil.conf
  nginx/uwsgi_params
  nginx/win-utf
Labels: 🚀 Config, ⭐️ Feat

#74 Fix/#73 커서 페이지네이션 버그 수정
  logbat_view/src/main/java/info/logbat_view/common/payload/CursorPaginationResult.java
  logbat_view/src/main/java/info/logbat_view/common/util/UUIDConvertor.java
  logbat_view/src/main/java/info/logbat_view/domain/log/application/LogViewService.java
  logbat_view/src/main/java/info/logbat_view/domain/log/domain/Log.java
  logbat_view/src/main/java/info/logbat_view/domain/log/domain/LogData.java
  logbat_view/src/main/java/info/logbat_view/domain/log/domain/service/LogService.java
  logbat_view/src/main/java/info/logbat_view/domain/log/presentation/LogViewController.java
  logbat_view/src/main/java/info/logbat_view/domain/log/presentation/payload/request/LogCursorRequest.java
  logbat_view/src/main/java/info/logbat_view/domain/log/repository/LogDataRepository.java
  logbat_view/src/test/java/info/logbat_view/common/util/UUIDConvertorTest.java
  logbat_view/src/test/java/info/logbat_view/domain/log/application/LogViewServiceTest.java
  logbat_view/src/test/java/info/logbat_view/domain/log/domain/service/LogServiceTest.java
Labels: 🐞 Bug

#77 Feat/#76 Nginx 요청을 구분한다
  nginx/sites-available/default
Labels: ⭐️ Feat

#78 Feat/#75 Logbat Java SDK 프로젝트 세팅 및 테스트
  sdk/java/logbat-sdk/.gitignore
  sdk/java/logbat-sdk/build.gradle
  sdk/java/logbat-sdk/gradle/wrapper/gradle-wrapper.jar
  sdk/java/logbat-sdk/gradle/wrapper/gradle-wrapper.properties
  sdk/java/logbat-sdk/gradlew
  sdk/java/logbat-sdk/gradlew.bat
  sdk/java/logbat-sdk/settings.gradle
  sdk/java/logbat-sdk/src/main/java/info/logbat/logback/LogbatAppender.java
Labels: ⭐️ Feat

#79 Feat/#72 AWS Lamda 테스트 환경 만들기
  lamda/.gitignore
  lamda/README.md
  lamda/package-lock.json
  lamda/package.json
  lamda/src/index.ts
  lamda/tsconfig.json
Labels: ⭐️ Feat

#83 Refactor/#82 LogData 필드 변경
  logbat_view/src/main/java/info/logbat_view/domain/log/domain/Log.java
  logbat_view/src/main/java/info/logbat_view/domain/log/domain/LogData.java
  logbat_view/src/main/java/info/logbat_view/domain/log/domain/enums/LogLevel.java
  logbat_view/src/test/java/info/logbat_view/domain/log/application/LogViewServiceTest.java
  logbat_view/src/test/java/info/logbat_view/domain/log/domain/service/LogServiceTest.java
Labels: 🔄 Refactor

#85 Feat/#81 로그 레벨 세분화
  logbat/src/main/java/info/logbat/domain/log/domain/Log.java
  logbat/src/main/java/info/logbat/domain/log/domain/enums/Level.java
  logbat/src/main/java/info/logbat/domain/log/repository/LogRepository.java
Labels: ⭐️ Feat

#92 Refactor/#91 Log 저장 시 appKey 대신 appId를 저장하도록 수정
  logbat/src/main/java/info/logbat/domain/log/application/LogService.java
  logbat/src/main/java/info/logbat/domain/log/domain/Log.java
  logbat/src/main/java/info/logbat/domain/log/repository/LogRepository.java
  logbat/src/main/java/info/logbat/domain/project/repository/AppJpaRepository.java
  logbat/src/test/java/info/logbat/domain/log/application/LogServiceTest.java
  logbat/src/test/java/info/logbat/domain/log/repository/LogRepositoryTest.java
  logbat/src/test/java/info/logbat/domain/project/domain/log/domain/LogTest.java
Labels: 🔄 Refactor

#90 Feat/#89 Log Insert 시 비동기 Bulk Insert 하도록 구현
  logbat/src/main/java/info/logbat/domain/log/repository/AsyncLogProcessor.java
  logbat/src/main/java/info/logbat/domain/log/repository/AsyncLogRepository.java
  logbat/src/main/java/info/logbat/domain/log/repository/LogRepository.java
  logbat/src/main/java/info/logbat/domain/log/repository/SynchronousLogRepository.java
  logbat/src/main/resources/application.properties
  logbat/src/main/resources/application.yml
  logbat/src/test/java/info/logbat/domain/log/application/LogServiceTest.java
  logbat/src/test/java/info/logbat/domain/log/repository/AsyncLogProcessorTest.java
  logbat/src/test/java/info/logbat/domain/log/repository/AsyncLogRepositoryTest.java
  logbat/src/test/java/info/logbat/domain/log/repository/SynchronousLogRepositoryTest.java
Labels: ⭐️ Feat

#95 Feat/#94 App Id Caching 기능 추가
  logbat/src/main/java/info/logbat/common/config/CachingConfiguration.java
  logbat/src/main/java/info/logbat/domain/log/application/LogService.java
  logbat/src/main/java/info/logbat/domain/project/application/AppService.java
  logbat/src/test/java/info/logbat/domain/log/application/LogServiceTest.java
Labels: ⭐️ Feat, 🔄 Refactor

#103 Refactor/#102 Log 저장 API 리팩토링
  logbat/src/main/java/info/logbat/domain/log/application/LogService.java
  logbat/src/main/java/info/logbat/domain/log/presentation/LogController.java
  logbat/src/main/java/info/logbat/domain/log/presentation/payload/request/CreateLogRequest.java
  logbat/src/main/java/info/logbat/domain/log/repository/AsyncLogProcessor.java
  logbat/src/main/java/info/logbat/domain/log/repository/AsyncLogRepository.java
  logbat/src/main/java/info/logbat/domain/log/repository/LogRepository.java
  logbat/src/main/java/info/logbat/domain/log/repository/SynchronousLogRepository.java
  logbat/src/test/java/info/logbat/dev/util/ThreadLocalLongAdderTest.java
  logbat/src/test/java/info/logbat/domain/log/application/LogServiceTest.java
  logbat/src/test/java/info/logbat/domain/log/presentation/LogControllerTest.java
  logbat/src/test/java/info/logbat/domain/log/repository/AsyncLogProcessorTest.java
  logbat/src/test/java/info/logbat/domain/log/repository/AsyncLogRepositoryTest.java
  logbat/src/test/java/info/logbat/domain/log/repository/SynchronousLogRepositoryTest.java
Labels: 🔄 Refactor, 💇🏻‍♀️ Style, 🧪 TEST

#105 Feat/#101 JS SDK 고도화
  nginx/sites-available/default
  sdk/js/src/index.ts
Labels: ⭐️ Feat, 🔄 Refactor

#104 Feat/#99 Logbat Java SDK 최소 기능 구현
  sdk/java/logbat-sdk/build.gradle
  sdk/java/logbat-sdk/src/main/java/info/logbat/LogbatFactory.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/adapter/logback/LogbatAppender.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/application/LogSendRequestFactory.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/application/Logbat.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/config/LogbatConfig.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/config/LogbatConfigLoader.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/domain/logbat/AppKey.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/domain/options/LogbatOptions.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/exception/InvalidAppKeyException.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/infrastructure/AsyncLogWriter.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/infrastructure/LogBuffer.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/infrastructure/LogProcessScheduler.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/infrastructure/LogSender.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/infrastructure/payload/LogSendRequest.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/logback/LogbatAppender.java
  sdk/java/logbat-sdk/src/test/java/info/logbat/application/LogSendRequestFactoryTest.java
  sdk/java/logbat-sdk/src/test/java/info/logbat/config/LogbatConfigLoaderTest.java
  sdk/java/logbat-sdk/src/test/java/info/logbat/domain/logbat/AppKeyTest.java
  sdk/java/logbat-sdk/src/test/java/info/logbat/domain/options/LogbatOptionsTest.java
  sdk/java/logbat-sdk/src/test/java/info/logbat/infrastructure/LogBufferTest.java
  sdk/java/logbat-sdk/src/test/java/info/logbat/infrastructure/LogSenderTest.java
  sdk/java/logbat-sdk/src/test/resources/application.properties
  sdk/java/logbat-sdk/src/test/resources/application.yml
Labels: ⭐️ Feat

#106 Feat/#80 Project, App View 생성
  logbat_meta/build.gradle
  logbat_meta/src/main/java/info/logbat_meta/LogbatMetaApplication.java
  logbat_meta/src/main/java/info/logbat_meta/domain/project/application/AppService.java
  logbat_meta/src/main/java/info/logbat_meta/domain/project/domain/App.java
  logbat_meta/src/main/java/info/logbat_meta/domain/project/presentation/AppController.java
  logbat_meta/src/main/java/info/logbat_meta/domain/project/presentation/ViewController.java
  logbat_meta/src/main/java/info/logbat_meta/domain/project/presentation/payload/request/AppCreateRequest.java
  logbat_meta/src/main/java/info/logbat_meta/domain/project/presentation/payload/response/AppCommonResponse.java
  logbat_meta/src/main/java/info/logbat_meta/domain/project/presentation/payload/response/ProjectCommonResponse.java
  logbat_meta/src/main/resources/application.yml
  logbat_meta/src/main/webapp/WEB-INF/views/common_head.jsp
  logbat_meta/src/main/webapp/WEB-INF/views/create_app.jsp
  logbat_meta/src/main/webapp/WEB-INF/views/create_project.jsp
  logbat_meta/src/main/webapp/WEB-INF/views/project_detail.jsp
  logbat_meta/src/main/webapp/WEB-INF/views/project_not_found.jsp
  logbat_meta/src/main/webapp/WEB-INF/views/projects.jsp
  logbat_meta/src/test/java/info/logbat_meta/domain/project/application/AppServiceTest.java
  logbat_meta/src/test/java/info/logbat_meta/domain/project/application/ProjectServiceTest.java
  logbat_meta/src/test/java/info/logbat_meta/domain/project/domain/AppTest.java
  logbat_meta/src/test/java/info/logbat_meta/domain/project/presentation/AppControllerTest.java
  logbat_meta/src/test/java/info/logbat_meta/domain/project/presentation/ProjectControllerTest.java
Labels: ⭐️ Feat, 💇🏻‍♀️ Style

#109 Feat/#108: JAVA SDK 배포
  docs/info/logbat/logbat-sdk/0.1.0/logbat-sdk-0.1.0.jar
  docs/info/logbat/logbat-sdk/0.1.0/logbat-sdk-0.1.0.pom
Labels: ⭐️ Feat

#114 Refactor/#112 Property File 파싱 로직 변경
  sdk/java/logbat-sdk/build.gradle
  sdk/java/logbat-sdk/src/main/java/info/logbat/LogBatFactory.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/LogbatFactory.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/adapter/logback/LogBatAppender.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/application/LogBat.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/application/Logbat.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/config/LogBatConfig.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/config/LogBatConfigLoader.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/config/LogbatConfig.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/config/LogbatConfigLoader.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/domain/logbat/AppKey.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/domain/options/LogBatOptions.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/domain/options/LogbatOptions.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/exception/InvalidAppKeyException.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/exception/InvalidOptionException.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/infrastructure/LogProcessScheduler.java
  sdk/java/logbat-sdk/src/main/java/info/logbat/infrastructure/LogSender.java
  sdk/java/logbat-sdk/src/test/java/info/logbat/config/LogBatConfigLoaderTest.java
  sdk/java/logbat-sdk/src/test/java/info/logbat/config/LogbatConfigLoaderTest.java
  sdk/java/logbat-sdk/src/test/java/info/logbat/domain/logbat/AppKeyTest.java
  sdk/java/logbat-sdk/src/test/java/info/logbat/domain/options/LogBatOptionsTest.java
  sdk/java/logbat-sdk/src/test/java/info/logbat/domain/options/LogbatOptionsTest.java
  sdk/java/logbat-sdk/src/test/java/info/logbat/infrastructure/LogBufferTest.java
  sdk/java/logbat-sdk/src/test/java/info/logbat/infrastructure/LogSenderTest.java
Labels: 📑 Docs, 🔄 Refactor, 💇🏻‍♀️ Style

#115 Feat/#113 로그 요청 목록 유효성 검사 기능 구현
  logbat/src/main/java/info/logbat/domain/log/presentation/LogController.java
  logbat/src/main/java/info/logbat/domain/log/presentation/validation/LogRequestsValidator.java
  logbat/src/main/java/info/logbat/domain/log/presentation/validation/ValidLogRequests.java
  logbat/src/test/java/info/logbat/domain/log/presentation/LogControllerTest.java
Labels: ⭐️ Feat

#119 Feat/#118 /favicon.ico에 대한 파일 내려주기 추가
  nginx/sites-available/default
  nginx/snippets/favicon.conf
Labels: 💇🏻‍♀️ Style

#124 Refactor/#123 성능 최적화 - .stream() 제거
  logbat/src/main/java/info/logbat/domain/log/application/LogService.java
  logbat/src/main/java/info/logbat/domain/log/domain/values/LogData.java
  logbat/src/main/java/info/logbat/domain/log/presentation/LogController.java
  logbat/src/main/java/info/logbat/domain/log/presentation/validation/LogRequestsValidator.java
  logbat/src/main/java/info/logbat/domain/log/presentation/validation/ValidLogRequests.java
  logbat/src/test/java/info/logbat/domain/log/presentation/LogControllerTest.java
Labels: 🔄 Refactor
